[terminal]

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 12 

[window]
padding.x = 8
padding.y = 8
# decorations = "None"
startup_mode = "Windowed" # "Maximized"

[general]
import = [
  "./moonfly.toml"
]

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
